drop trigger if exists "new-landing-page-contact-form" on "public"."landing_page_contact_form";

alter table "public"."users_metadata" drop constraint "users_metadata_organization_id_fkey";

create table "public"."companies" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


alter table "public"."companies" enable row level security;

create table "public"."prompt_blocks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "company_id" uuid,
    "organization_id" uuid,
    "user_id" uuid,
    "type" text,
    "content" jsonb,
    "title" jsonb,
    "description" jsonb,
    "published" boolean not null default false
);


alter table "public"."prompt_blocks" enable row level security;

create table "public"."prompt_folders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "organization_id" uuid,
    "parent_folder_id" bigint,
    "title" jsonb,
    "description" jsonb,
    "company_id" uuid,
    "type" text
);


alter table "public"."prompt_folders" enable row level security;

alter table "public"."organizations" add column "banner_url" text;

alter table "public"."organizations" add column "image_url" text;

alter table "public"."organizations" add column "website_url" text;

alter table "public"."prompt_templates" add column "blocks" bigint[];

alter table "public"."prompt_templates" add column "company_id" uuid;

alter table "public"."prompt_templates" add column "content" jsonb;

alter table "public"."prompt_templates" add column "description" jsonb;

alter table "public"."prompt_templates" add column "metadata" jsonb;

alter table "public"."prompt_templates" add column "organization_id" uuid;

alter table "public"."prompt_templates" add column "title" jsonb;

alter table "public"."prompt_templates" alter column "usage_count" set default '0'::bigint;

alter table "public"."users_metadata" drop column "organization_id";

alter table "public"."users_metadata" add column "company_id" uuid;

alter table "public"."users_metadata" add column "interests" text[];

alter table "public"."users_metadata" add column "job_industry" text;

alter table "public"."users_metadata" add column "job_seniority" text;

alter table "public"."users_metadata" add column "job_type" text;

alter table "public"."users_metadata" add column "organization_ids" uuid[];

alter table "public"."users_metadata" add column "pinned_folder_ids" bigint[];

alter table "public"."users_metadata" add column "pinned_template_ids" bigint[];

alter table "public"."users_metadata" add column "signup_source" text;

CREATE UNIQUE INDEX companies_pkey ON public.companies USING btree (id);

CREATE UNIQUE INDEX prompt_blocks_pkey ON public.prompt_blocks USING btree (id);

CREATE UNIQUE INDEX prompt_folders_pkey ON public.prompt_folders USING btree (id);

alter table "public"."companies" add constraint "companies_pkey" PRIMARY KEY using index "companies_pkey";

alter table "public"."prompt_blocks" add constraint "prompt_blocks_pkey" PRIMARY KEY using index "prompt_blocks_pkey";

alter table "public"."prompt_folders" add constraint "prompt_folders_pkey" PRIMARY KEY using index "prompt_folders_pkey";

alter table "public"."prompt_blocks" add constraint "prompt_blocks_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) not valid;

alter table "public"."prompt_blocks" validate constraint "prompt_blocks_company_id_fkey";

alter table "public"."prompt_blocks" add constraint "prompt_blocks_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) not valid;

alter table "public"."prompt_blocks" validate constraint "prompt_blocks_organization_id_fkey";

alter table "public"."prompt_blocks" add constraint "prompt_blocks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."prompt_blocks" validate constraint "prompt_blocks_user_id_fkey";

alter table "public"."prompt_folders" add constraint "prompt_folders_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) not valid;

alter table "public"."prompt_folders" validate constraint "prompt_folders_company_id_fkey";

alter table "public"."prompt_folders" add constraint "prompt_folders_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) not valid;

alter table "public"."prompt_folders" validate constraint "prompt_folders_organization_id_fkey";

alter table "public"."prompt_folders" add constraint "prompt_folders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."prompt_folders" validate constraint "prompt_folders_user_id_fkey";

alter table "public"."prompt_templates" add constraint "prompt_templates_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) not valid;

alter table "public"."prompt_templates" validate constraint "prompt_templates_company_id_fkey";

alter table "public"."prompt_templates" add constraint "prompt_templates_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) not valid;

alter table "public"."prompt_templates" validate constraint "prompt_templates_organization_id_fkey";

alter table "public"."users_metadata" add constraint "users_metadata_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) not valid;

alter table "public"."users_metadata" validate constraint "users_metadata_company_id_fkey";

grant delete on table "public"."companies" to "anon";

grant insert on table "public"."companies" to "anon";

grant references on table "public"."companies" to "anon";

grant select on table "public"."companies" to "anon";

grant trigger on table "public"."companies" to "anon";

grant truncate on table "public"."companies" to "anon";

grant update on table "public"."companies" to "anon";

grant delete on table "public"."companies" to "authenticated";

grant insert on table "public"."companies" to "authenticated";

grant references on table "public"."companies" to "authenticated";

grant select on table "public"."companies" to "authenticated";

grant trigger on table "public"."companies" to "authenticated";

grant truncate on table "public"."companies" to "authenticated";

grant update on table "public"."companies" to "authenticated";

grant delete on table "public"."companies" to "service_role";

grant insert on table "public"."companies" to "service_role";

grant references on table "public"."companies" to "service_role";

grant select on table "public"."companies" to "service_role";

grant trigger on table "public"."companies" to "service_role";

grant truncate on table "public"."companies" to "service_role";

grant update on table "public"."companies" to "service_role";

grant delete on table "public"."prompt_blocks" to "anon";

grant insert on table "public"."prompt_blocks" to "anon";

grant references on table "public"."prompt_blocks" to "anon";

grant select on table "public"."prompt_blocks" to "anon";

grant trigger on table "public"."prompt_blocks" to "anon";

grant truncate on table "public"."prompt_blocks" to "anon";

grant update on table "public"."prompt_blocks" to "anon";

grant delete on table "public"."prompt_blocks" to "authenticated";

grant insert on table "public"."prompt_blocks" to "authenticated";

grant references on table "public"."prompt_blocks" to "authenticated";

grant select on table "public"."prompt_blocks" to "authenticated";

grant trigger on table "public"."prompt_blocks" to "authenticated";

grant truncate on table "public"."prompt_blocks" to "authenticated";

grant update on table "public"."prompt_blocks" to "authenticated";

grant delete on table "public"."prompt_blocks" to "service_role";

grant insert on table "public"."prompt_blocks" to "service_role";

grant references on table "public"."prompt_blocks" to "service_role";

grant select on table "public"."prompt_blocks" to "service_role";

grant trigger on table "public"."prompt_blocks" to "service_role";

grant truncate on table "public"."prompt_blocks" to "service_role";

grant update on table "public"."prompt_blocks" to "service_role";

grant delete on table "public"."prompt_folders" to "anon";

grant insert on table "public"."prompt_folders" to "anon";

grant references on table "public"."prompt_folders" to "anon";

grant select on table "public"."prompt_folders" to "anon";

grant trigger on table "public"."prompt_folders" to "anon";

grant truncate on table "public"."prompt_folders" to "anon";

grant update on table "public"."prompt_folders" to "anon";

grant delete on table "public"."prompt_folders" to "authenticated";

grant insert on table "public"."prompt_folders" to "authenticated";

grant references on table "public"."prompt_folders" to "authenticated";

grant select on table "public"."prompt_folders" to "authenticated";

grant trigger on table "public"."prompt_folders" to "authenticated";

grant truncate on table "public"."prompt_folders" to "authenticated";

grant update on table "public"."prompt_folders" to "authenticated";

grant delete on table "public"."prompt_folders" to "service_role";

grant insert on table "public"."prompt_folders" to "service_role";

grant references on table "public"."prompt_folders" to "service_role";

grant select on table "public"."prompt_folders" to "service_role";

grant trigger on table "public"."prompt_folders" to "service_role";

grant truncate on table "public"."prompt_folders" to "service_role";

grant update on table "public"."prompt_folders" to "service_role";

create policy "Enable read access for all users"
on "public"."prompt_blocks"
as permissive
for select
to public
using (true);


create policy "Enable write access for all users"
on "public"."users_metadata"
as permissive
for insert
to public
with check (true);



